# Generated by Django 3.2.3 on 2021-05-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='rest',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='caller',
            name='waiter',
            field=models.IntegerField(null=True),
        ),
    ]
