# Generated by Django 3.2.3 on 2021-05-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0002_auto_20210531_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='table',
            field=models.IntegerField(null=True),
        ),
    ]
