# Generated by Django 3.2.3 on 2021-06-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0003_caller_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caller',
            name='rest',
            field=models.CharField(max_length=1024, null=True, verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='caller',
            name='table',
            field=models.IntegerField(null=True, verbose_name='Столик'),
        ),
        migrations.AlterField(
            model_name='caller',
            name='waiter',
            field=models.IntegerField(null=True, verbose_name='TgId'),
        ),
    ]
