# Generated by Django 3.2.3 on 2021-06-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0004_auto_20210601_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='qr',
            field=models.ImageField(null=True, upload_to='', verbose_name='QR'),
        ),
        migrations.AddField(
            model_name='caller',
            name='url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
    ]
