# Generated by Django 3.2.3 on 2021-06-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0005_auto_20210602_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caller',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR'),
        ),
        migrations.AlterField(
            model_name='caller',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
