# Generated by Django 3.2.3 on 2021-06-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0006_auto_20210602_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caller',
            name='url',
        ),
    ]
