# Generated by Django 3.2.3 on 2021-06-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0007_remove_caller_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
