# Generated by Django 3.2.3 on 2021-06-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0009_remove_caller_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR'),
        ),
    ]
