# Generated by Django 3.2.3 on 2021-06-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0011_remove_caller_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='qr',
            field=models.URLField(blank=True, null=True, verbose_name='QR'),
        ),
    ]
