# Generated by Django 3.2.3 on 2021-06-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0012_caller_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('restaurant', models.CharField(max_length=100, null=True, verbose_name='Ресторан')),
                ('table', models.IntegerField(null=True, verbose_name='Номер столика')),
            ],
        ),
        migrations.AlterField(
            model_name='caller',
            name='rest',
            field=models.CharField(max_length=100, null=True, verbose_name='Ресторан'),
        ),
    ]
