# Generated by Django 3.2.3 on 2021-06-18 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0013_auto_20210618_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=17, verbose_name='Телефон')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('n_tables', models.IntegerField(verbose_name='Кол-во столиков')),
                ('vk', models.URLField(verbose_name='VK')),
                ('inst', models.URLField(verbose_name='Inst')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rest', models.CharField(max_length=100, null=True, verbose_name='Ресторан')),
                ('url', models.URLField(null=True, verbose_name='Ссылка')),
                ('qr', models.URLField(null=True, verbose_name='QR')),
            ],
        ),
        migrations.DeleteModel(
            name='Caller',
        ),
    ]
