# Generated by Django 3.2.3 on 2021-06-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0018_auto_20210618_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='inst',
            field=models.URLField(blank=True, null=True, verbose_name='Inst'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='vk',
            field=models.URLField(blank=True, null=True, verbose_name='VK'),
        ),
    ]
