# Generated by Django 3.2.3 on 2021-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0019_auto_20210618_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='back_ident',
            field=models.CharField(blank=True, help_text='Оставить пустым!!!', max_length=300, null=True, verbose_name='Back название'),
        ),
        migrations.AlterField(
            model_name='log',
            name='restaurant',
            field=models.CharField(max_length=300, null=True, verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant',
            field=models.CharField(help_text='Название, которое отображается на странице.', max_length=100, verbose_name='Front название'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='tables',
            field=models.CharField(max_length=200, null=True, verbose_name='Столы'),
        ),
    ]
