# Generated by Django 3.2.3 on 2021-06-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0020_auto_20210619_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер стола'),
        ),
    ]
