# Generated by Django 3.2.3 on 2021-06-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0021_alter_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(verbose_name='Номер стола'),
        ),
    ]
