# Generated by Django 3.2.3 on 2021-06-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0022_alter_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Slug столы'),
        ),
    ]
