# Generated by Django 3.2.3 on 2021-06-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0023_table_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Slug столы'),
        ),
    ]
