# Generated by Django 3.2.3 on 2021-06-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0024_alter_table_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='back_ident',
            new_name='back_identif',
        ),
    ]
